### ISSUE TITLE
Error packaging

### ISSUE THREAD

**Issue by BliXem1** [gspannu/OPNsense-Plugins#1]
OPNsense repository update completed. 837 packages processed.
Updating guru-repo repository catalogue...
Fetching meta.conf: 100%    163 B   0.2kB/s    00:01
Fetching packagesite.pkg: 100%    1 KiB   1.2kB/s    00:01
Processing entries:   0%
pkg: wrong architecture: FreeBSD:13:amd64 instead of FreeBSD:14:amd64
pkg: repository guru-repo contains packages with wrong ABI: FreeBSD:13:amd64
Processing entries: 100%
Unable to update repository guru-repo
Error updating repositories!

Any idea's?

**Comment by gspannu** [comment]
What version of OPNsense are you trying this with? 
**24.1.x or 24.7.x?**

I think I need to upgrade the plugin to work with 24.7 (did not have time to get around to this.... but will do so).

**Comment by BliXem1** [comment]
2.4.7.x :-)

**Comment by gspannu** [comment]
I believe I have fixed the issue, however you will have to delete the previous version and reinstall.

Instructions below.

In OPNsense GUI...

1) Disable Blocky (reenable some other DNS resolver/ or if already disabled then continue)

2) Ensure that your internet is working.

3) Delete previous version of Blocky
In OPNsense shell...
```
sudo rm /usr/local/etc/pkg/repos/guru-repo.conf
sudo pkg update -f
```

4) Reinstall Blocky plugin from new location
```
sudo fetch -o /usr/local/etc/pkg/repos/guru-repo.conf https://raw.githubusercontent.com/gspannu/OPN-Plugins/master/guru-repo.conf;
sudo pkg update -f
sudo pkg update -f
```
yes, please run `pkg update -f` twice !

5) Back in OPNsense GUI, you should see Blocky in your System>Firmware>Plugins

6) Add the new repo
7) Refresh OPNsense GUI, and enable Blocky in Services>BlockyDNS

_This should retain your previous blocky config file...._

This new repo should now work with both 24.1 and 24.7 (and hopefully future versions as well). 

**Please test and let me know.**
If all works, I will archive this repository and make a reference to the new Github repo..

The new GitHub repo is [here](https://github.com/gspannu/OPN-Plugins) for reference.

**Comment by gspannu** [comment]
@BliXem1 :
Can you please check/ test as above and report.

Many thanks...

**Comment by BliXem1** [comment]
Hi @gspannu , i'm sorry, but I revert back to PFsense. I hope someone else can test this.

**Comment by gspannu** [comment]
> Hi @gspannu , i'm sorry, but I revert back to PFsense. I hope someone else can test this.

No worries, thankyou
